# Конфигурация для Nixpacks (Coolify: Build Pack = nixpacks)
# Документация: https://nixpacks.com/docs/configuration/file

# Явно задаём среду NodeJS совместимую с @vitejs/plugin-vue@6.x
# Требование плагина: ^20.19.0 или >=22.12.0. Используем Node.js 22.x (>=22.12.0).
[phases.setup]
nixPkgs = ["nodejs_22", "yarn"]

[variables]
# Отключаем автоопределение версии Node, используем только nixPkgs
NIXPACKS_NO_MUSL = "1"

[phases.install]
# Используем yarn install c frozen lockfile (соответствует текущей сборке)
cmds = [
  "yarn install --frozen-lockfile"
]

[phases.build]
# Сборка приложения Quasar/Vite
cmds = [
  "quasar build"
]
