[phases.setup]
nixPkgs = ["nodejs_22", "yarn", "curl"]
nixpkgsArchive = "d1fa2249e3375835132333541638935533963df9"


[phases.install]
cmds = [
    "yarn install --frozen-lockfile"
]

[phases.build]
cmds = ["yarn build"]
