[phases.setup]
# Nix уже ставит node и yarn — ничего руками не качаем
nixPkgs = ["nodejs_20", "yarn", "curl"]


[phases.install]
cmds = [
    "yarn install --frozen-lockfile"
]

[phases.build]
cmds = ["yarn build"]
