# Конфигурация для Nixpacks (Coolify: Build Pack = nixpacks)
# Причина падения: образ с nixpkgs подтянул nodejs_22 версии 22.11.0,
# а @vitejs/plugin-vue@6.x требует ^20.19.0 или >=22.12.0. Фиксим,
# принудительно устанавливая Node.js 22.12.0 в фазе setup и кладём его в PATH.

[phases.setup]
# Базовые пакеты и утилиты
nixPkgs = ["nodejs_22", "yarn", "curl"]
# Скачиваем официальный бинарник Node 22.12.0 под текущую архитектуру и добавляем в PATH
cmds = [
    "set -e",
    "NODE_VER=22.12.0",
    "ARCH=$(uname -m); case \"$ARCH\" in x86_64) TARARCH=linux-x64;; aarch64) TARARCH=linux-arm64;; *) echo 'Unsupported arch:' $ARCH; exit 1;; esac",
    "mkdir -p /opt",
    "curl -fsSL https://nodejs.org/dist/v$NODE_VER/node-v$NODE_VER-$TARARCH.tar.xz | tar -xJ -C /opt",
    "ln -sfn /opt/node-v$NODE_VER-$TARARCH /opt/node",
    # ВАЖНО: не используем многострочный printf — из-за этого Dockerfile ломался на строке 'export'.
    "echo 'export PATH=/opt/node/bin:$PATH' >> /root/.profile",
    # Проверка версии
    "source /root/.profile && node -v && npm -v"
]

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
NIXPACKS_NO_MUSL = "1"
# Делаем Node из /opt доступным в каждом RUN без source
PATH = "/opt/node/bin:$PATH"

[phases.install]
cmds = [
    "corepack enable || true",
    "yarn install --frozen-lockfile"
]

[phases.build]
# Сборка приложения Quasar/Vite
cmds = [
    "source /root/.profile && quasar build"
]
